services:
  yolo:
    environment:
      - gpus=1
      # - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]
    devices:
      - "device=0"
      # - "nvidia.com/gpu=all"

  pose:
    environment:
      - gpus=1
      # - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
              - capabilities: [gpu]
    devices:
      - "device=0"
      # - "nvidia.com/gpu=all"
